### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory:

### ISSUE THREAD

**Issue by xmxxiong** [BMPixel/moffee#3]
Traceback (most recent call last):
  File "/Users/xm/miniconda3/envs/grag/bin/moffee", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/moffee/cli.py", line 78, in live
    run(markdown, output=None, live=True)
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/moffee/cli.py", line 24, in run
    render_handler()
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/moffee/builder.py", line 117, in build
    output_html = copy_assets(output_html, asset_dir).replace(asset_dir, "assets")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/site-packages/moffee/utils/file_helper.py", line 94, in copy_assets
    shutil.copy(url, new_path)
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/xm/miniconda3/envs/grag/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^

**Comment by BMPixel** [comment]
I see. May I know the content of your markdown document? Does it contain a link to a folder in your document?

**Comment by xmxxiong** [comment]
# Markdown Title
Use **bold** and *italic* for emphasis.

- Extended syntax like ~~strikethroughs~~ is supported.

## Page 1
Some text

## Page 2
This sentence will appear on the second slide.
## Page 1
Text on the first slide
---
Text on the next slide.

Text on the left.
***
![Image on the right](https://placehold.co/600x400)


Top bun
___
Patty on the left
***
Lettuce on the right
___
Bottom bun

---
layout: content # HTML template. Use "centered" for centered alignment.
resource_dir: "." # Relative URLs are based on this directory.
default_h1: false # Inherit H1 from previous slides if not defined.
default_h2: true  # Inherit H2
default_h3: true  # Inherit H3
---

---
layout: content
background-color: darkgray
color: white
---

# A refined landing page
Our journey begins here
@(layout=content, background-image='url("https://placehold.co/600x400")')

**Comment by xmxxiong** [comment]
my first export is ok, but second export get this error

**Comment by BMPixel** [comment]
It should be working now. Reinstall moffee above v0.2.3.
